version: '3.4'

services:
  btest:
    image: ${DOCKER_REGISTRY-}btest
    build:
      context: .
      dockerfile: src/Btest/Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/webApp/Dockerfile


  test:
    image: ${DOCKER_REGISTRY-}test
    build:
      context: .
      dockerfile: src/test/Dockerfile

